apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: megamart-staging

resources:
  - ../../base/catalog-service
  - ../../base/order-service
  - ../../base/network-policies

patches:
  - path: catalog-patch.yaml
  - path: order-patch.yaml
