apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-autoscaler
  namespace: kube-system
  labels:
    app.kubernetes.io/name: cluster-autoscaler
  annotations:
    # Cluster Autoscaler IRSA Role Annotation
    eks.amazonaws.com/role-arn: arn:aws:iam::227493789634:role/megamart-cluster-autoscaler-irsa-role
    eks.amazonaws.com/sts-regional-endpoints: "true"
