apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: order-service-hpa
  namespace: megamart-prod
  labels:
    app.kubernetes.io/name: order-service
    app.kubernetes.io/part-of: megamart-ecommerce
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: order-service
  minReplicas: 3
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
        - type: Pods
          value: 4
          periodSeconds: 15
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 20
          periodSeconds: 60
      selectPolicy: Min
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: order-service-pdb
  namespace: megamart-prod
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app.kubernetes.io/name: order-service
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: megamart-prod
resources:
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml
  - hpa.yaml
  - pdb.yaml
