apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-service-sa
  namespace: megamart-prod
  labels:
    app.kubernetes.io/name: order-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: megamart-ecommerce
  annotations:
    # IAM Roles for Service Accounts (IRSA)
    eks.amazonaws.com/role-arn: arn:aws:iam::227493789634:role/megamart-order-service-irsa-role
    eks.amazonaws.com/sts-regional-endpoints: "true"
    eks.amazonaws.com/token-expiration: "86400"
