apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  namespace: megamart-prod
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: catalog-service
          env:
            - name: ENVIRONMENT
              value: "production"
            - name: LOG_LEVEL
              value: "INFO"
